name: "Update"
on:
  push:
    branches:
      master
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    concurrency: update-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
    - name: prepare
      run: |
        .github/exec nix-build --version
    - name: git-setup
      run: |
        .github/exec git config --global user.name 'Cole Botkens'
        .github/exec git config --global user.email 'cole.mickens+colebot@gmail.com'
    - name: update
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_nixpkgs_wayland }}"
      run: |
        set -xeuo pipefail
        export CI_JOB_ID="${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
        .github/exec ./update.sh
    - name: push
      run: |
        .github/exec git push origin HEAD
